### PR TITLE
An example implementation of `get_territory`

### PR DESCRIPTION
**Pull request by symroe**
This isn't intended to be merged, it's simply a spike of a way to
add a `get_territory` implementation.

### CODE REVIEW

**Comment by chris48s** [comment]
Do you actually need to add this? Bear in mind you can already call `get_code('ctry')`, which returns:

> The code for the appropriate country (i.e. one of the four constituent countries of the UK or Crown dependencies -the Channel Islands or the Isle of Man) to which each postcode is assigned.

ONSPD/ONSUD:
> E92000001 = England;
> W92000004 = Wales;
> S92000003 = Scotland;

ONSPD only:
> N92000002 = Northern Ireland;
> L93000001= Channel Islands;
> M83000003= Isle of Man


e.g:
```py
>>> from uk_geo_utils.geocoders import AddressBaseGeocoder
>>> g = AddressBaseGeocoder('SA8 4DA')
>>> g.get_code('ctry')
'W92000004'
>>> g.get_code('ctry', "10010020128")
'W92000004'
```

I'd tend to just call `get_code('ctry')` (and then re-code that in the client app if needed) tbh.

**Comment by symroe** [comment]
Ah, my misreading of the docs - I'd not spotted `ctry` and thought `rgn` was the only way to get this. 

As for if the method is needed anyway: I guess it's a question of how much this package is trying to do to make the underlying data more accessible. If you don't know what's in the data, or don't read the docs fully (can you imagine...), it's easier to see a list of helper methods. Although, given that our actual implementation (e.g., where I'd like to use it) doesn't even use this table, the conversation is a little academic!

It was also useful for me to spike this to get my head around the code and how it might be implemented - once we've figured out the actual implementation in WDIV then the chances are I'll delete this PR anyway.

Thanks for pointing out the `ctry` column!

**Comment by chris48s** [comment]
> given that our actual implementation (e.g., where I'd like to use it) doesn't even use this table, the conversation is a little academic!

Right yeah. I'd lost sight of the fact that the 'ONSUD' table in WDIV isn't actually the ONSUD anymore (or possibly won't be post- https://github.com/DemocracyClub/UK-Polling-Stations/pull/2703 ?). In that case, I'd probably bodge this somewhere in https://github.com/DemocracyClub/UK-Polling-Stations/blob/master/polling_stations/apps/data_finder/helpers/geocoders.py (where the other bodges are bodged :see_no_evil:  ) based on the first char of local auth code (which is kind of what you're doing here anyway).

**Comment by symroe** [comment]
> based on the first char of local auth code

Yeah, but this is now a register code, so :upside_down_face:

**Comment by chris48s** [comment]
> Yeah, but this is now a register code, so :upside_down_face:

I see. I hadn't focussed that https://github.com/DemocracyClub/UK-Polling-Stations/pull/2743 changes the codes in your lookup table to register codes instead of GSS codes.
Was that an intended or unintended consequence? I'd say conceptually it isn't really the right model tbh.
WDIV doesn't have this concept, but if you think about this in terms of the Every Election data model where `Organisation` (register code) is separate from `OrganisationGeography` (GSS code), something like phone number or an email address is a fact to attach to an `Organisation`, but here you are literally storing "this point is inside this polygon" (and if the polygon changes, so does the mapping), so conceptually this really a fact about an `OrganisationGeography` (GSS code) not a fact about an `Organisation` (register code).

There are various possible solutions for this:
- Store GSS codes in the `UprnToCouncil` model
- Store country on the `councils` table when you import councils
- Create a `ctry` column on the `UprnToCouncil`  when you generate/populate that

but I won't attempt to dictate which you should adopt. Either way, they're really all solutions that happen inside WDIV.

---

> I guess it's a question of how much this package is trying to do to make the underlying data more accessible

So one thing that is probably worth going over here is why this library exists, the assumptions it is based on and how things have changed over time.. This is something I discussed with @GeoWill in quite a bit of detail in Bristol, but you were doing.. something else at the time so I'll go back over it.. Classic Chris wall o' text incoming:

At the time I wrote this library, our thinking was that we were going to solve postcode centroids once-and-for-all across WDIV, Every Election and WCIVF and the way we were going to do that was that all of those applications would have their own copy of AddressBase, ONSUD and ONSPD. Basically the thinking behind this library is that all three of those applications are going to need a django model to store each of those three data sources, an import script to import each of them and some code to query it all. So with that future in mind, it seemed sensible to do that in one place instead of three. Then we don't have to write/maintain the same code in lots of different places, as the world changes around us (e.g: https://github.com/DemocracyClub/uk-geo-utils/commit/fcc5adf15ec04e4bbb875d5d11c37234de7ced50 , https://github.com/DemocracyClub/uk-geo-utils/commit/1a45dd066d0650f1f6849c60735c2ed2a5b9b33e , etc) we can update it in one place, all three applications use consistent querying code. There's also potential to create a generically useful package (hence it being a package that is published to PyPI instead of an internal package that we just pull in as a VCS dependency, like [dc_signup_form](https://github.com/DemocracyClub/dc_signup_form) for example). So really the design goal was just to be a quite generic library to keep the models for storing AddressBase, ONSUD and ONSPD, import scripts for getting data into them and a fairly thin wrapper for querying them in one place instead of three..

This plan encoded several assumptions which turned out to be bad as time went on:

### Assumption 1: We will want to use AddressBase, ONSPD and ONSUD in at least three codebases which Democracy Club maintains.

Although this was the direction we were thinking in at the time, this future never really materialized for various reasons. I won't re-hash them all here, but the status quo is that WDIV uses this package (but does some acrobatics around it - more on that later). EE uses only the model/import script for OSNPD. WCIVF doesn't use it at all.

I'm not really sure what your future vision looks like.
One possible future is that you finish/merge #2703 and that makes it easier for other applications to interop with each other using UPRN (this is _one_ of the reasons why WDIV is currently the only app that uses addressbase but not the _only_ reason) and you can really go to town on making more use of AddressBase.
..but based on what you said on Slack the other day, maybe another future is the EC take on WDIV/EE and WCIVF becomes an application that consumes the EC's API and augments that data with extras from candidates.DC (completely deferring the issue of postcodes/addresses to the EC's API).. or maybe you just stop running WCIVF altogether? I don't really know what your thinking is.
I guess the thing I can say is: If the future looks like DC maintaining multiple apps with an AddressBase table, conceptually this library probably does provide some value but if it looks like one app with an AddressBase table, it probably doesn't help so much.

### Assumption 2: ONSUD is a useful data source and this will be the main way we map UPRNs to councils (and possibly other geographies)

At the point I created this library, this was quite a good assumption and we did use the ONSUD for this for some time (in fact I think we were still using ONSUD for the last election that wasn't cancelled due to COVID), but over time it has become clear there are several problems with this.

* ONSUD's publishing schedule lags behind ONSPD's by quite a way. For example, when there are local auth changes the new councils usually come into existence on 1 April. There is a new ONSPD available with the new codes some time in April, but the ONSUD doesn't reflect the changes until the next release after the October BoundaryLine so whereas there is a ONSPD release available before elections in early May with the change we need, we don't get a corresponding ONSUD until something like November/December that year. This means we need to work around that problem.
* The differing publication schedules of OSNPD/ONSUD and AddressBase make it possible for us to have UPRNS that do exist in our AddressBase table but don't exist in our ONSUD table etc (and allows for various other problems and inconsistencies).
* ONSUD is massive and we only really use one column from it in WDIV. We can use less disk space and improve performance by just importing the one column we actually need.

so @GeoWill has now moved us to a model where in WDIV we create a table based on our `AddressBase` and `Council` tables with just the one column we need. This has the advantage that every UPRN in our AB table is in it, and its (by definition) completely consistent with our AB/Council tables. Then we tell this library that is our "ONSUD" table so that we can continue to use the Geocoder classes in this library (which are actually quite useful).

### Assumption 3: New councils being created is quite a rare occurrence

In fairness, this wasn't an unfounded assumption when we made it. At the time, the last local government structural changes had happened in 2009 and prior to that I think it was 1998. The way things have panned out, there have been a number of these changes in recent years and it looks likely that there will be more in the near future. What this means is that to accommodate this we need to be able to bodge the geocoders a bit to deal with data sources not reflecting these changes yet (in fairness moving away from ONSUD helps with this but there's still a patch where we need to deal with new councils in WDIV but the new ONSPD isn't out yet). The upshot of all this is that we end up doing a bit more acrobatics in WDIV to patch the geocoder classes from `uk-geo-utils` rather than using them directly (and that's probably going to be the norm for a bit now). Having the geocoders live in a different package makes that a bit more complicated.


### So what does all that mean?

So when you take all that together, the situation that currently exists is that the one application that makes the most use of this code has to implement a couple of different workarounds to use it and most of the other benefits we had in mind never really materialized. So essentially, a chunk of WDIV's codebase lives in a different repo and that makes it harder to change. I don't have the context to know what direction you're heading in with this stuff, but if the long term position is the only app that uses most of this stuff is WDIV, having `uk-geo-utils` as a separate package isn't really buying you much and it is creating some problems to work around. In that context you might be better off to just inline most of this stuff back into an app in the WDIV codebase, write it off as a failed experiment and that would actually allow you to remove several bodges/workarounds from WDIV and evolve this stuff in an easier way (because all the code lives just in one repo, you don't need to care about the impact of changes to it on anything else and PRs don't need to be co-ordinated over 2 codebases).

**Pull request closed without merging**
